# Ruta base
ruta_base: "C:\\PROYECTOS\\PyCharm\\pythonrun\\recuperacion_informacion_modelos_lenguaje\\tfm"

# Configuracion de los Logs
logs_config:
  ruta_salida_logs: "logs"
  format: "%(asctime)s - %(levelname)s - %(message)s"
  level: "DEBUG"

# Configuracion de la Base de Datos de Mensajes (Contexto)

# Configuracion de Base de Datos Vectorial
vectorial_database:
  ruta: "Faiss"
  serialized_database: "db"
  file_retriever: "retriever.pkl"
  file_vector_index: "vector_index.pkl"
  parameters_tokenizador:
    name_model_llm: llama3
    name_model_tokenizador: llama3
    return_tensors: pt
    max_length: 512
    truncation: true
    padding: max_length
    temperature: 0.0

# WebScrapping
scrapping:
  ruta: "ObtencionDatos"
  descarga_datos: "datos"
  dataset_index:
    campos_metadata:
      - url
      - titulo
    campo_texto:
      - texto
  fuentes:
    boe: "https://www.boe.es/"
    bocyl: "https://bocyl.jcyl.es/"

# Modelo LLM principal
llm_oepia:
  ruta: "OEPIA"
  parameters_modelo:
    llm_model: llama3
    temperature: 0.0

# Modelos:
